### ISSUE TITLE
Supported RL framework?

### ISSUE THREAD

**Issue by Wang4758** [f1tenth/f1tenth_gym#43]
Hi there,

Thanks for your nice work! I tried to train an RL agent using stable baselines for your gym. But I've got several bugs since your gym is slightly different than the standard OpenAI gym. I was wondering which RL framework did you use in your RL experiments or which RL framework is compatible with your gym? Here are a few differences I encountered for stable baselines (these are rather easy to solve but I was just wondering which RL framework would work out of box with your env)

- no `observation_space` and `action_space` defined
- `reset` method returns more than just obs
- to be discovered...

**Comment by hzheng40** [comment]
Hi,
Thanks for checking out our work.
This was a product of our research work and at the time we didn't use an RL framework. The gym API has also changed quite a bit since we've made this.
Currently, I'm the only maintainer of this and I'm aware of updates that I'll need to make to fully support different RL frameworks.

The plan for the upcoming summer is to first update some of the functions to the current version of Gym API. And update control input types to support more than just speed and velocity, and also fully define the observation and action spaces correctly.

Stay tuned for updates! Again, thanks for checking this out!
