### ISSUE TITLE
Error while setting up the project

### ISSUE THREAD

**Issue by naman-gupta99** [f1tenth/f1tenth_gym#60]
**Describe the bug**
On running the command `pip3 install -e .` I get the following error:
<img width="886" alt="image" src="https://github.com/f1tenth/f1tenth_gym/assets/32611803/364ff5fc-a594-436c-9487-6b6c580f1790">

**To Reproduce**
1. Create a virtual env.
2. run `pip3 install -e .`

**Expected behavior**
The dependencies should get installed and set up should be complete without errors.

**Desktop (please complete the following information):**
 - OS: macOS Ventura v13.3.1

**Comment by 9elmo6** [comment]
Hello, 

I was facing the same issue. 

Check the latest pull request dev_gymnasium, which is still not merged to the main branch. The waypoint_follow example is working for me now.

**Comment by hzheng40** [comment]
Could you please report your python versions? The current gym version in setup.py is the last one that supports the API that we're using.

**Comment by 9elmo6** [comment]
My Python version is 3.8.8

**Comment by naman-gupta99** [comment]
Got it. The dev_gymnasium changes do work.

**Comment by hzheng40** [comment]
Can you try `pip3 install --upgrade pip setuptools`? This looks like a setuptools error.

**Comment by tianyilim** [comment]
Hi, I know this is closed, but according to [this thread](https://answers.ros.org/question/396439/setuptoolsdeprecationwarning-setuppy-install-is-deprecated-use-build-and-pip-and-other-standards-based-tools/), do make sure you install `pip3 install setuptools==58.2.0` if you are in Ubuntu 22.04 + ROS Humble. If not, the rest of your ROS workspace will not build!

This is because the installation method for Python has changed.
